# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/sg3_utils-1.49-Linux/development
Summary:        sg3_utils built using CMake
Name:           sg3_utils-devel
Version:        1.49
Release:        1
License:        BSD-2-Clause and GPL-2.0-or-later
Group:          unknown
Vendor:         Douglas Gilbert


















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS

%define _unpackaged_files_terminate_build 0





%description
libsgutils2 development library and include files for sg3_utils

# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
%dir /usr/include/scsi
/usr/include/scsi/sg_cmds.h
/usr/include/scsi/sg_cmds_basic.h
/usr/include/scsi/sg_cmds_extra.h
/usr/include/scsi/sg_cmds_mmc.h
/usr/include/scsi/sg_io_linux.h
/usr/include/scsi/sg_json.h
/usr/include/scsi/sg_json_sg_lib.h
/usr/include/scsi/sg_lib.h
/usr/include/scsi/sg_lib_data.h
/usr/include/scsi/sg_lib_names.h
/usr/include/scsi/sg_linux_inc.h
/usr/include/scsi/sg_nvme.h
/usr/include/scsi/sg_pr2serr.h
/usr/include/scsi/sg_pt.h
/usr/include/scsi/sg_pt_linux.h
/usr/include/scsi/sg_pt_linux_missing.h
/usr/include/scsi/sg_pt_win32.h
/usr/include/scsi/sg_snt.h
/usr/include/scsi/sg_unaligned.h
/usr/lib/libsgutils2.so




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.49-1
  Generated by CPack RPM (no Changelog file were provided)


